### ISSUE TITLE
Please add 15 nodes prism element

### ISSUE THREAD

**Issue by vadim-z** [PetrKryslUCSD/GmshImport.jl#1]
I noticed that Gmsh elements 18 and 19 (https://gmsh.info/doc/texinfo/gmsh.html#MSH-file-format) are missing.

 Elt #18 (a 'serendipity-type' prism) is of particular interest for me because Gmsh generates it for my mesh with Recombine command and Mesh.SecondOrderIncomplete = 1.

**Comment by PetrKryslUCSD** [comment]
I would be happy to entertain a PR, if you have the time.

**Comment by PetrKryslUCSD** [comment]
On second thought, I saw an opportunity to revise the interface. I added also the element types you requested to the default.
